package com.codeops.registry.dto.response;

import com.codeops.registry.entity.enums.ConfigTemplateType;

import java.time.Instant;
import java.util.UUID;

/** Response containing a generated or stored configuration template. */
public record ConfigTemplateResponse(
    UUID id,
    UUID serviceId,
    String serviceName,
    ConfigTemplateType templateType,
    String environment,
    String contentText,
    Boolean isAutoGenerated,
    String generatedFrom,
    Integer version,
    Instant createdAt,
    Instant updatedAt
) {}
