package com.codeops.registry.entity;

import com.codeops.registry.entity.enums.ConfigTemplateType;
import jakarta.persistence.*;
import lombok.*;

/**
 * Generated or stored configuration template for a service in a specific environment.
 *
 * <p>Templates can be auto-generated from registry data or manually created.
 * Each template is versioned to track changes over time.</p>
 */
@Entity
@Table(name = "config_templates",
        uniqueConstraints = @UniqueConstraint(name = "uk_ct_service_type_env",
                columnNames = {"service_id", "template_type", "environment"}),
        indexes = @Index(name = "idx_ct_service_id", columnList = "service_id"))
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class ConfigTemplate extends BaseEntity {

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "service_id", nullable = false)
    private ServiceRegistration service;

    @Enumerated(EnumType.STRING)
    @Column(name = "template_type", nullable = false, length = 30)
    private ConfigTemplateType templateType;

    @Column(name = "environment", nullable = false, length = 50)
    private String environment;

    @Column(name = "content_text", nullable = false, columnDefinition = "TEXT")
    private String contentText;

    @Builder.Default
    @Column(name = "is_auto_generated", nullable = false)
    private Boolean isAutoGenerated = true;

    @Column(name = "generated_from", length = 200)
    private String generatedFrom;

    @Builder.Default
    @Column(name = "version", nullable = false)
    private Integer version = 1;
}
